apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-stack
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kafka-stack
  template:
    metadata:
      labels:
        app: kafka-stack
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: Always
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
        ports:
        - containerPort: 2181
      - name: kafka
        image: confluentinc/cp-kafka:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - until [ $(echo "ruok" | nc -w 2 -l -p 2181 | grep imok) ]; do sleep 2; done;
        env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kafka:9092
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: localhost:2181
          - name: KAFKA_ADVERTISED_LISTENERS
            value: PLAINTEXT://kafka:9092
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
            value: "1"
          - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
            value: "1"
        ports:
        - containerPort: 9092
