apiVersion: apps/v1
kind: Deployment
metadata:
  name: webproxy
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: webproxy
  template:
    metadata:
      labels:
        app: webproxy
    spec:
      containers:
      - name: webproxy
        image: 482053628475.dkr.ecr.eu-central-1.amazonaws.com/usupport-webproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
