version: "3.8"
services:
  webproxy:
    container_name: webproxy
    restart: "unless-stopped"
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - gateway
    volumes:
      - ./webproxy/nginx-production.conf:/etc/nginx/nginx.conf
      - ./webproxy/logs/:/var/log/nginx/
      - /etc/nginx/ssl/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - USupportNet

  gateway:
    container_name: gateway
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    depends_on:
      - client
      - provider
      - video
      - payments
      - notifications
      - messaging
      - admin
      - email
    volumes:
      - ./gateway:/home/node/app
    env_file:
      - ./gateway/.env.production
    ports:
      - 3000:3000
    expose:
      - 3000
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet

  client:
    container_name: client
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./client/service:/home/node/app
    env_file:
      - ./client/service/.env.production
    ports:
      - 3001:3001
    expose:
      - 3001
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet

  provider:
    container_name: provider
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./provider/service:/home/node/app
    env_file:
      - ./provider/service/.env.production
    ports:
      - 3002:3002
    expose:
      - 3002
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet
  
  video:
    container_name: video
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./video/service:/home/node/app
    env_file:
      - ./video/service/.env.production
    ports:
      - 3003:3003
    expose:
      - 3003
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet
  
  payments:
    container_name: payments
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./payments/service:/home/node/app
    env_file:
      - ./payments/service/.env.production
    ports:
      - 3004:3004
    expose:
      - 3004
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet

  notifications:
    container_name: notifications
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./notifications/service:/home/node/app
    env_file:
      - ./notifications/service/.env.production
    ports:
      - 3005:3005
    expose:
      - 3005
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet

  messaging:
    container_name: messaging
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./messaging/service:/home/node/app
    env_file:
      - ./messaging/service/.env.production
    ports:
      - 3006:3006
    expose:
      - 3006
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet

  admin:
    container_name: admin
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./admin/service:/home/node/app
    env_file:
      - ./admin/service/.env.production
    ports:
      - 3007:3007
    expose:
      - 3007
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet

  email:
    container_name: email
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./email/service:/home/node/app
    env_file:
      - ./email/service/.env.production
    ports:
      - 3008:3008
    expose:
      - 3008
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet

  cms:
    container_name: cms
    build:
      context: ./cms
      dockerfile: Dockerfile
    restart: "unless-stopped"
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - ./cms/package-lock.json:/opt/package-lock.json
      - ./cms/.env.production:/opt/app/.env
    ports:
      - 3009:1337
    expose:
      - 3009
    networks:
      - USupportNet

  user:
    container_name: user
    restart: "unless-stopped"
    image: node:16.5.0-alpine3.13
    working_dir: /home/node/app
    volumes:
      - ./user/service:/home/node/app
    env_file:
      - ./user/service/.env.production
    ports:
      - 3010:3010
    expose:
      - 3010
    command: >
      sh -c "npm ci &&
              npm run prod"
    networks:
      - USupportNet

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - USupportNet

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - USupportNet

  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes: 
      - ./cache/redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - USupportNet

networks:
  USupportNet:
