version: "3.8"
services:
  webproxy:
    container_name: webproxy
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - USupportNet

  gateway:
    container_name: gateway
    image: node:16.5.0-alpine3.13
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - USupportNet

  client:
    container_name: client
    image: node:16.5.0-alpine3.13
    ports:
      - 3001:3001
    expose:
      - 3001
    networks:
      - USupportNet

  provider:
    container_name: provider
    image: node:16.5.0-alpine3.13
    ports:
      - 3002:3002
    expose:
      - 3002
    networks:
      - USupportNet

  video:
    container_name: video
    image: node:16.5.0-alpine3.13
    ports:
      - 3003:3003
    expose:
      - 3003
    networks:
      - USupportNet

  payments:
    container_name: payments
    image: node:16.5.0-alpine3.13
    ports:
      - 3004:3004
    expose:
      - 3004
    networks:
      - USupportNet

  notifications:
    container_name: notifications
    image: node:16.5.0-alpine3.13
    ports:
      - 3005:3005
    expose:
      - 3005
    networks:
      - USupportNet

  messaging:
    container_name: messaging
    image: node:16.5.0-alpine3.13
    ports:
      - 3006:3006
    expose:
      - 3006
    networks:
      - USupportNet

  admin:
    container_name: admin
    image: node:16.5.0-alpine3.13
    ports:
      - 3007:3007
    expose:
      - 3007
    networks:
      - USupportNet

  email:
    container_name: email
    image: node:16.5.0-alpine3.13
    ports:
      - 3008:3008
    expose:
      - 3008
    networks:
      - USupportNet

  cms:
    container_name: cms
    build:
      context: ./cms
      dockerfile: Dockerfile
    ports:
      - 3009:3009
    expose:
      - 3009
    networks:
      - USupportNet

  user:
    container_name: user
    image: node:16.5.0-alpine3.13
    ports:
      - 3010:3010
    expose:
      - 3010
    networks:
      - USupportNet

  masterdb:
    container_name: masterDB
    build:
      context: ./databases/masterDB
      dockerfile: Dockerfile
    ports:
      - "5435:5432"
    networks:
      - USupportNet

  piidb:
    container_name: piiDB
    build:
      context: ./databases/piiDB
      dockerfile: Dockerfile
    ports:
      - "5436:5432"
    networks:
      - USupportNet

  clinicaldb:
    container_name: clinicalDB
    build:
      context: ./databases/clinicalDB
      dockerfile: Dockerfile
    ports:
      - "5437:5432"
    networks:
      - USupportNet

  cmsdb:
    container_name: cmsDB
    build:
      context: ./databases/cmsDB
      dockerfile: Dockerfile
    ports:
      - "5438:5432"
    networks:
      - USupportNet

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - USupportNet

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      - USupportNet

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - USupportNet

networks:
  USupportNet:
